export const products = [
  {
    id: 1,
    name: 'UV Protection Sunglasses',
    brand: 'SunShade',
    price: 24.99,
    rating: 4.8,
    stock: 15,
    description:
      'Premium polarized sunglasses with 100% UV protection. Perfect for beach days and outdoor adventures.',
    image: 'https://i.ibb.co.com/dwR13f5C/uv-sunglass.avif',
    category: 'Accessories',
  },
  {
    id: 2,
    name: 'Lightweight Summer Hoodie',
    brand: 'BeachVibe',
    price: 39.99,
    rating: 4.6,
    stock: 8,
    description:
      'Breathable and stylish summer hoodie made with premium cotton fabric.',
    image: 'https://i.ibb.co.com/TxW8Sm3S/summer-hoodie.avif',
    category: 'Clothing',
  },
  {
    id: 3,
    name: 'Aloe Vera Sunscreen SPF 50',
    brand: 'GlowSkin',
    price: 18.99,
    rating: 4.9,
    stock: 20,
    description:
      'Lightweight, non-greasy sunscreen with aloe vera for maximum skin protection.',
    image: 'https://i.ibb.co.com/pgpD6wL/aloe-vera.avif',
    category: 'Skincare',
  },
  {
    id: 4,
    name: 'Straw Beach Hat',
    brand: 'CoastalStyle',
    price: 15.99,
    rating: 4.5,
    stock: 12,
    description:
      'Wide brim straw hat perfect for sun protection and summer fashion.',
    image: 'https://i.ibb.co.com/1f70PkcV/straw-hat.avif',
    category: 'Accessories',
  },
  {
    id: 5,
    name: 'Summer Flip Flops',
    brand: 'WaveWalk',
    price: 12.99,
    rating: 4.7,
    stock: 25,
    description:
      'Comfortable and durable flip flops designed for beach and pool days.',
    image: 'https://i.ibb.co.com/zztMfV7/flip-flops.avif',
    category: 'Footwear',
  },
  {
    id: 6,
    name: 'Portable Beach Cooler Bag',
    brand: 'SunTrip',
    price: 29.99,
    rating: 4.4,
    stock: 7,
    description:
      'Insulated cooler bag to keep your drinks cold all day at the beach.',
    image: 'https://i.ibb.co.com/XZzzmsNL/beach-cooler.avif',
    category: 'Accessories',
  },
  {
    id: 7,
    name: 'Quick-Dry Beach Towel',
    brand: 'AquaSoft',
    price: 22.99,
    rating: 4.7,
    stock: 18,
    description:
      'Ultra-absorbent and quick-dry microfiber towel, perfect for beach and travel use.',
    image: 'https://i.ibb.co.com/Sw1w8yk5/towel.avif',
    category: 'Accessories',
  },
  {
    id: 8,
    name: 'Men’s Casual Linen Shirt',
    brand: 'BreezeWear',
    price: 34.99,
    rating: 4.5,
    stock: 10,
    description:
      'Lightweight linen shirt designed for maximum comfort during hot summer days.',
    image: 'https://i.ibb.co.com/HLfy8vjW/shirt.avif',
    category: 'Clothing',
  },
  {
    id: 9,
    name: 'Hydrating Face Mist',
    brand: 'FreshGlow',
    price: 14.99,
    rating: 4.6,
    stock: 22,
    description:
      'Refreshing face mist infused with natural extracts to keep your skin hydrated all day.',
    image: 'https://i.ibb.co.com/Lhzd1prD/face-mist.avif',
    category: 'Skincare',
  },
  {
    id: 10,
    name: 'Men’s Beach Pants',
    brand: 'SunnyStep',
    price: 32.99,
    rating: 4.6,
    stock: 18,
    description:
      'Comfortable and breathable pants designed for men to enjoy relaxed days at the beach.',
    image: 'https://i.ibb.co.com/yF8X8wjd/men-s-pant.avif',
    category: 'Clothing',
  },
];
